In [9]:
import re
import pandas as pd
from random import choice

from ruwordnet import RuWordNet

from pymystem3 import Mystem

from pymorphy3 import MorphAnalyzer

from sklearn.model_selection import train_test_split

In [10]:
df = pd.read_csv('ru_cefr_short.csv')
df

,fragment,textbook-assigned cefr level
0,"Весной, летом и осенью почти каждую субботу он...",1
1,"Все говорят, что мама хорошая хозяйка. А ещё н...",1
2,На каждой двери красные плакаты и красные фона...,1
3,"Я считаю деньги, в час обедаю в кафе, а потом ...",1
4,Магазин «Чёрный квадрат» открывается в 9 часов...,1
...,...,...
7317,Утечка мозгов стала ключевым трендом междунаро...,6
7318,"По оценкам менеджеров «Промы», такая ситуация ...",6
7319,"Но это не мы, а техно-мемы заполоняют мир благ...",6
7320,Mapillary использует программное обеспечение д...,6
7321,"Новое роботакси, разрабатываемое Маском, сможе...",6

In [11]:
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['fragment'].values,
    df['textbook-assigned cefr level'].values,
    test_size=0.2,
    random_state=42,
    stratify=df['textbook-assigned cefr level']
)

len(train_texts)

5857

In [12]:
texts_to_augment = []

for i in range(len(train_labels)):
  if train_labels[i] == 6:
    texts_to_augment.append(train_texts[i])


len(texts_to_augment)

120

In [13]:
def tokenize(text):
    return re.findall(r"\w+|[^\w\s]", text, flags=re.UNICODE)

def detokenize(tokens):
    text = ""
    for i, tok in enumerate(tokens):
        if i == 0:
            text += tok
            continue

        if tok in ",.!?:;)]}»":
            text += tok
        elif tokens[i - 1] in "([«":
            text += tok
        else:
            text += " " + tok
    return text

In [14]:
m = Mystem()

def lemmatize(text):
  lemmas = m.lemmatize(text)
    
  lemmas = [i for i in lemmas if i != ' ' and i != '\n']

  return lemmas

In [15]:
morph = MorphAnalyzer()

GOOD_POS = {
    "NOUN",   
    "ADJF", 
    "ADJS",
    "VERB",   
    "INFN"   
}

def is_replaceable_word(word):
    parses = morph.parse(word)
    if not parses:
        return False

    p = parses[0]
    pos = p.tag.POS

    if pos not in GOOD_POS:
        return False

    # исключаем местоимения и местоименные слова
    if pos == "NPRO":
        return False

    # исключаем местоименное прилагательное: этот, мой, какой, всякий
    if "Apro" in p.tag:
        return False

    return True

In [16]:
morph = MorphAnalyzer()

wn = RuWordNet("/home/tyumen/baseline_libs/myenv/lib/python3.12/site-packages/ruwordnet/static/ruwordnet-2021.db")

clean_title = lambda title: re.sub(r'\s*\([^)]*\)', '', title).strip()


def get_antonyms(word):
    parse = morph.parse(word)[0]
    lemma = parse.normal_form.lower()

    antonyms = []

    for sense in wn.get_senses(lemma):
        synset = sense.synset
        if synset is None:
            continue

        antonym_synsets = getattr(synset, "antonyms", [])

        for ant_synset in antonym_synsets:
            for ant_sense in ant_synset.senses:
                antonym = ant_sense.name.lower()
                antonym = clean_title(antonym)

                if " " in antonym:
                    continue
                if antonym == lemma:
                    continue

                antonyms.append(antonym)

    antonyms = list(dict.fromkeys(antonyms))
    return antonyms

In [17]:
with open('new_vocab_a1.txt', 'r'):
    file = open('new_vocab_a1.txt')
    a1 = file.readlines()

with open('new_vocab_a2.txt', 'r'):
    file = open('new_vocab_a2.txt')
    a2 = file.readlines()

with open('new_vocab_b1.txt', 'r'):
    file = open('new_vocab_b1.txt')
    b1 = file.readlines()

with open('new_vocab_b2.txt', 'r'):
    file = open('new_vocab_b2.txt')
    b2 = file.readlines()

with open('new_vocab_c1.txt', 'r'):
    file = open('new_vocab_c1.txt')
    c1 = file.readlines()


a1 = set([w.replace('\ufeff', '').strip() for w in a1 if w.strip()])
a2 = set([w.replace('\ufeff', '').strip() for w in a2 if w.strip()])
b1 = set([w.replace('\ufeff', '').strip() for w in b1 if w.strip()])
b2 = set([w.replace('\ufeff', '').strip() for w in b2 if w.strip()])
c1 = set([w.replace('\ufeff', '').strip() for w in c1 if w.strip()])

print(len(a1), len(a2),len(b1), len(b2), len(c1))


only_a1 = a1
only_a2 = a2 - a1
only_b1 = b1 - a2 - a1
only_b2 = b2 - b1 - a2 - a1
only_c1 = c1 - b2 - b1 - a2 - a1

print(len(only_a1), len(only_a2), len(only_b1), len(only_b2), len(only_c1))

923 1493 2821 5867 11961
923 580 1334 3142 6441

In [18]:
def rank_antonyms(antonyms):
    c1 = []
    b2 = []
    b1 = []
    a2 = []
    a1 = []
    
    for antonym in antonyms:
        if antonym in only_c1:
            c1.append(antonym)
        elif antonym in only_b2:
            b2.append(antonym)
        elif antonym in only_b1:
            b1.append(antonym)
        elif antonym in only_a2:
            a2.append(antonym)
        elif antonym in only_a1:
            a1.append(antonym)

    ranked_antonyms = c1 + b2 + b1+ a2+ a1
    return ranked_antonyms

In [19]:
INFLECTABLE_GRAMMEMES = {
    # число
    "sing", "plur",

    # род
    "masc", "femn", "neut",

    # падеж
    "nomn", "gent", "datv", "accs", "ablt", "loct",
    "gen1", "gen2", "acc2", "loc1", "loc2", "voct",

    # одуш/неодуш
    "anim", "inan",

    # глагольные категории
    "past", "pres", "futr",
    "1per", "2per", "3per",
    "indc", "impr",

    # вид
    "perf", "impf",

    # для кратких/полных прилагательных и т.п.
    "Supr", "COMP"
}

def preserve_case(source, target):
    if source.isupper():
        return target.upper()
    if source[0].isupper():
        return target.capitalize()
    return target

def inflect_antonym_like(source_word, ranked_antonyms):
    source_parses = morph.parse(source_word)
    if not source_parses:
        return None
    source_parse = source_parses[0]

    for antonym_lemma in ranked_antonyms:
        antonym_parses = morph.parse(antonym_lemma)
        if antonym_parses:
            source_pos = source_parse.tag.POS
        
            antonym_parse = None
            for p in antonym_parses:
                if p.tag.POS == source_pos:
                    antonym_parse = p
                    break
        
            if antonym_parse is None:
                antonym_parse = antonym_parses[0]
        
            # вытаскиваем у исходного слова нужные граммемы
            source_grammemes = set(source_parse.tag.grammemes)
            needed_grammemes = source_grammemes & INFLECTABLE_GRAMMEMES
        
            # пробуем поставить синоним в ту же форму
            inflected = antonym_parse.inflect(needed_grammemes)

            if inflected:
                return preserve_case(source_word, inflected.word)
        

    return None

In [20]:
augmented_texts = []
texts = []

for text in texts_to_augment:
    tokens = tokenize(text)
    words_to_replace = {}

    for idx, word in enumerate(tokens):
        if is_replaceable_word(tokens[idx]):
            words_to_replace[idx] = word

    words_to_antonyms = {}

    to_print = {}
    
    for key in words_to_replace.keys():
        antonyms = get_antonyms(tokens[key])
        ranked_antonyms = rank_antonyms(antonyms)

        if len(ranked_antonyms) > 0:

            new_form = inflect_antonym_like(words_to_replace[key], ranked_antonyms)
            if new_form:
                words_to_antonyms[key] = new_form
            
    new_text = []

    for i in range(len(tokens)):
        if i in words_to_antonyms.keys():
            new_text.append(words_to_antonyms[i])
        else:
            new_text.append(tokens[i])

    new_text = detokenize(new_text)

    if new_text != text:
        print(text)
        print(new_text)
        print('\n')

        augmented_texts.append(new_text)
        texts.append(text)

3:38–3:54 Собственно, сама по себе радиация незаразна. Например, мощными дозами излучения от тех же самых изотопов часто стерилизуют фрукты и овощи, а также лечат людей.
3: 38 – 3: 54 Собственно, сама по себе радиация незаразна. Например, мощными дозами излучения от тех же самых изотопов часто стерилизуют фрукты и овощи, а также лечат людей.


«Сразу после несчастного случая я вспомнил про видео с какими-то невероятными протезами — ловкими, красивыми, управляемыми силой мысли.»
«Сразу после несчастного случая я вспомнил про видео с какими - то невероятными протезами — неловкими, дурными, управляемыми силой мысли.»


Директор Института социального анализа и прогнозирования РАНХиГС Татьяна Малева объясняет, что в мире сегодня действительно обострилась конкуренция за человеческий капитал, это основной ресурс и мотор развития.
Директор Института социального анализа и прогнозирования РАНХиГС Татьяна Малева объясняет, что в мире сегодня действительно обострилась конкуренция за бесчеловечный капитал, это основной ресурс и мотор развития.


Почему мы ещё долго не увидим самоуправляемые машины на дорогах? Новости о достижениях автомобильной промышленности и открытия в сфере искусственного интеллекта создают впечатление, что автоуправляемые машины вот-вот появятся на дорогах.
Почему мы ещё долго не увидим самоуправляемые машины на дорогах? Новости о достижениях автомобильной промышленности и открытия в сфере натурального интеллекта создают впечатление, что автоуправляемые машины вот - вот появятся на дорогах.


0:25–1:24 Большинство людей при этом слове впадает в панику, но на самом деле, мы окружены радиацией со всех сторон. Её излучают небо, земля, дома, другие люди и даже бананы!
0: 25 – 1: 24 Большинство людей при этом слове впадает в панику, но на самом деле, мы окружены радиацией со всех сторон. Её излучают небо, земля, дома, другие люди и даже бананы!


Богатеть, жрать, гулять, жениться на молодой и красивой – лишь бы другие оценили. И даже притворяться богатым, здоровым и весёлым. Наконец, нагреть руки на мнимостях.
Богатеть, жрать, гулять, жениться на молодой и дурной – лишь бы другие оценили. И даже притворяться богатым, здоровым и весёлым. Наконец, нагреть руки на мнимостях.


Иногда эти частицы-пули сталкиваются с атомами с такой силой, что выбивают из них электроны. Вот почему радиация называется «ионизирующее излучение».
Иногда эти частицы - пули сталкиваются с атомами с такой силой, что выбивают из них электроны. Вот почему радиация называется «ионизирующее излучение».


Утечка мозгов стала ключевым трендом международной миграции последних лет, уверены западные эксперты. На днях ВОИС обнародовала исследование, подтверждающее эту тенденцию и к тому же содержащее парадоксальные открытия.
Утечка мозгов стала ключевым трендом международной миграции предварительных лет, уверены западные эксперты. На днях ВОИС обнародовала исследование, подтверждающее эту тенденцию и к тому же содержащее парадоксальные открытия.


Как измерить мем и как зафиксировать факт его самовоспроизведения, передачи и распространения? Как правильно описать мем и определить его содержание? Вторая проблема связана с определением мема.
Как измерить мем и как зафиксировать факт его самовоспроизведения, передачи и распространения? Как правильно описать мем и определить его содержание? Вторая развязка связана с определением мема.


«Человек без тайности – пустая грамота» – есть такая пословица. Между тем скоростной ритм требует не только лаконичности и цепляющей броскости суждений, но и их частоты.
«Человек без тайности – содержательная грамота» – есть такая пословица. Между тем скоростной ритм требует не только лаконичности и цепляющей броскости суждений, но и их редкости.


Ведь в будущем новым приёмам придётся научиться не только самоуправляемым машинам, но и нам самим, чтобы удерживать созданную технику под контролем.
Ведь в будущем старым приёмам придётся научиться не только самоуправляемым машинам, но и нам самим, чтобы удерживать созданную технику под контролем.


В Пока ни один из изобретённых человеком протезов не может полностью заменить руку. Это особенно очевидно, когда необходимо совершить сложную манипуляцию — завязать шнурки, почистить картошку, достать карточку из кошелька.
В Пока ни один из изобретённых человеком протезов не может полностью заменить руку. Это особенно спорное, когда необходимо совершить несложную манипуляцию — завязать шнурки, почистить картошку, достать карточку из кошелька.


Фёдор Михайлович Достоевский родился 11 ноября 1821 года в Москве, в дворянской семье. В 16 лет Фёдор с братом переезжает в Петербург и поступает в военно-инженерное училище.
Фёдор Михайлович Достоевский родился 11 ноября 1821 года в Москве, в дворянской семье. В 16 лет Фёдор с братом переезжает в Петербург и поступает в военно - инженерное училище.


Идеалом ума, рассматривающего действительность, есть простота, полная ясность, полное понимание. Хорошо известно, что до тех пор, пока вы предмет не постигли, он для вас представляется сложным и туманным.
Идеалом ума, рассматривающего действительность, есть сложность, частичная ясность, частичное понимание. Хорошо известно, что до тех пор, пока вы предмет не постигли, он для вас представляется несложным и туманным.


Рекламирует свою продукцию, наведывается к потенциальным заказчикам. Словом, работает не покладая рук. Вот-вот, кажется, и покупателей не останется — ведь жалюзи служат долго. За то и любимы в народе.
Рекламирует свою продукцию, наведывается к потенциальным заказчикам. Словом, работает не покладая рук. Вот - вот, кажется, и покупателей не останется — ведь жалюзи служат долго. За то и любимы в народе.


Однако возникает достаточно много вопросов и проблем, связанных с применением меметики и её дальнейшим оформлением в науку. Первая — проблема измерения.
Однако возникает достаточно много вопросов и развязок, связанных с применением меметики и её дальнейшим оформлением в науку. Первая — развязка измерения.


Но конечная цель проекта художника кажется не столько практической, сколько концептуальной: Брайдл исследует, что происходит, когда в общество внедряются потенциально опасные или разрушительные технологии.
Но предварительная цель проекта художника кажется не столько практической, сколько концептуальной: Брайдл исследует, что происходит, когда в общество внедряются потенциально опасные или разрушительные технологии.


Ежегодно в мире проводят более миллиона ампутаций. Самая частая причина — диабет и сосудистые заболевания, а также травмы. В России в протезах рук и ног нуждается около 200 тысяч человек.
Ежегодно в мире проводят более миллиона ампутаций. Самая редкая причина — диабет и сосудистые заболевания, а также травмы. В России в протезах рук и ног нуждается около 200 тысяч человек.


Например, радиоизотопы, которые стреляют альфа- и бета-излучением, не могут пробить даже наружный слой кожи или пару сантиметров воздуха.
Например, радиоизотопы, которые стреляют альфа - и бета - излучением, не могут пробить даже наружный слой кожи или пару сантиметров воздуха.


По его словам, у протезов есть свои плюсы: например, не мёрзнут руки на морозе, и можно взять горячую кастрюлю и чайник, не опасаясь обжечься.
По его словам, у протезов есть свои плюсы: например, не мёрзнут руки на морозе, и можно взять холодную кастрюлю и чайник, не опасаясь обжечься.


Маршрут задаётся через планшет. Поехали! 00:01:00 Смотрите, как ловко обходит препятствия. Пешеходы на нерегулируемом переходе, как раз тут срабатывают датчики дальнего действия.
Маршрут задаётся через планшет. Поехали! 00: 01: 00 Смотрите, как ловко обходит препятствия. Пешеходы на нерегулируемом переходе, как раз тут срабатывают датчики недалёкого действия.


«Хорошие» мемы — это такие, которые обладают высокой выживаемостью в культурной среде, то есть привлекательны для людей, которые с готовностью копируют их на протяжении многих поколений.
«Дурные» мемы — это такие, которые обладают высокой выживаемостью в дикой среде, то есть привлекательны для людей, которые с готовностью копируют их на протяжении многих поколений.


Объяснение простое: население там большое, а образовательный уровень граждан в целом довольно высок и продолжает расти, то есть уехавших есть, кем заменить.
Объяснение непростое: население там большое, а образовательный уровень граждан в целом довольно высок и продолжает расти, то есть уехавших есть, кем заменить.


Но писателя не казнят, а смертную казнь в последнюю минуту заменяют Сибирской каторгой в Омске.
Но писателя не казнят, а смертную казнь в предварительную минуту заменяют Сибирской каторгой в Омске.


Меня утешает вот что: где есть зависимость, там есть и боль. Не всякий человек может пребывать всё время на открытом солнцепёке, лишённый тени одиночества.
Меня утешает вот что: где есть независимость, там есть и боль. Не всякий человек может пребывать всё время на секретном солнцепёке, лишённый тени одиночества.


Эти сюжеты известны ещё с античности и связаны с природой человека, но интернет придал им размах, а современные психологи возвели в доблесть.
Эти сюжеты известны ещё с античности и связаны с природой человека, но интернет придал им размах, а допотопные психологи возвели в доблесть.


Искусство по природе своей мистериально — обращено к глубинам человеческой психики, и поэтому сила его воздействия неисчерпаема, как неисчерпаемы смыслы метафор и образов, средствами которых оно выражает себя.
Искусство по природе своей мистериально — обращено к глубинам бесчеловечной психики, и поэтому сила его воздействия неисчерпаема, как неисчерпаемы смыслы метафор и образов, средствами которых оно выражает себя.


По оценкам менеджеров «Промы», такая ситуация абсолютно нереальна, так как потенциал рынка жалюзи в России едва ли не в тысячу раз превышает нынешний ежемесячный объём их продаж.
По оценкам менеджеров «Промы», такая ситуация абсолютно реальная, так как потенциал рынка жалюзи в России едва ли не в тысячу раз превышает нынешний ежемесячный объём их продаж.


Основные покупатели таких машин — предприятия и промышленное производство. Как можно решить проблему? Помочь беспилотным автомобилям более безопасно ориентироваться в наших городах смогут краудсорсинговые карты.
Основные покупатели таких машин — предприятия и промышленное производство. Как можно решить развязку? Помочь беспилотным автомобилям более безопасно ориентироваться в наших городах смогут краудсорсинговые карты.


Первое, самое общее свойство, качество ума — это постоянное сосредоточение мысли на определённом вопросе, предмете. С предметом, в области которого вы работаете, вы не должны расставаться ни на минуту.
Первое, самое локальное свойство, качество ума — это непостоянное сосредоточение мысли на определённом вопросе, предмете. С предметом, в области которого вы работаете, вы не должны расставаться ни на минуту.


Павлова называли «романтической, почти легендарной личностью», «гражданином мира», а друг учёного, писатель Герберт Уэллс, сказал о нём: «Это звезда, которая освещает мир, проливая свет на ещё не изведанные пути».
Павлова называли «романтической, почти легендарной личностью», «гражданином мира», а друг учёного, писатель Герберт Уэллс, сказал о нём: «Это звезда, которая освещает мир, проливая мрак на ещё не изведанные пути».


Пока беспилотные машины существуют в бета-версии, исследователи работают над системами, способными анализировать дорогу лучше, чем водитель-человек.
Пока беспилотные машины существуют в бета - версии, исследователи работают над системами, способными анализировать дорогу лучше, чем водитель - человек.


Почему машины не готовы принимать «разумные» решения? Ещё одна нерешённая проблема заключается в создании системы, которая может принимать разумные решения — регулировать скорость и менять полосы движения.
Почему машины не готовы принимать «бессмысленные» решения? Ещё одна нерешённая развязка заключается в создании системы, которая может принимать бессмысленные решения — регулировать скорость и менять полосы движения.


Действительность велика, беспредельна, бесконечна и разнообразна, она никогда не укладывается в рамки наших признанных понятий, наших самых последних знаний.
Действительность велика, беспредельна, конечная и разнообразна, она никогда не укладывается в рамки наших признанных понятий, наших самых предварительных знаний.


Но многие ли знают, что мемами интересуются сразу два направления в науке — мемология и меметика? И почему представители обоих говорят о том, что мы сегодня переживаем настоящую «мем-революцию»?
Но многие ли знают, что мемами интересуются сразу два направления в науке — мемология и меметика? И почему представители обоих говорят о том, что мы сегодня переживаем настоящую «мем - революцию»?


Даже тонкие интеллектуалы и изящные эстеты не забудут с ненавязчивой гордыней сообщить о свежих итальянских путешествиях, и освежающие брызги ворвутся в их высокую речь.
Даже бестактные интеллектуалы и изящные эстеты не забудут с ненавязчивой гордыней сообщить о усталых итальянских путешествиях, и освежающие брызги ворвутся в их высокую речь.


Она найдёт своё отражение в нескольких произведениях писателя, в том числе и его самом последнем и грандиозном романе «Братья Карамазовы».
Она найдёт своё отражение в нескольких произведениях писателя, в том числе и его самом предварительном и грандиозном романе «Братья Карамазовы».


«Я напрягаю две основные мышцы руки: “сгибатель” и “разгибатель”. Когда напрягаю верхнюю мышцу, два электрода “открывают” протез, когда нижнюю — “закрывают”», — объясняет он принцип работы своей бионической руки.
«Я напрягаю две основные мышцы руки: “ сгибатель ” и “ разгибатель ”. Когда напрягаю верхнюю мышцу, два электрода “ открывают ” протез, когда нижнюю — “ закрывают ”», — объясняет он принцип работы своей бионической руки.


Искусство составляет одну из высших сфер деятельности духа. Эта сторона искусства не есть что-то отвлечённое, мечтательное, безразличное; напротив, она заключает в себе многие области, заселённые живыми, конкретными образами. Чудная страна!
Искусство составляет одну из высших сфер деятельности духа. Эта сторона искусства не есть что - то отвлечённое, мечтательное, безразличное; напротив, она заключает в себе многие области, заселённые безжизненными, отвлечёнными образами. Чудная страна!


Заигрывание с публикой и зависимость от этого заигрывания неизбежно предопределяют фальшивую оптимистичность. Люди молчат о том, что они одни, что им страшно, что они ничтожны.
Заигрывание с публикой и независимость от этого заигрывания неизбежно предопределяют фальшивую оптимистичность. Люди молчат о том, что они одни, что им страшно, что они ничтожны.


Кроме того, среди мемов существует конкуренция, которая выражается в борьбе за место в человеческой памяти и за внимание, уделяемое мему. Что же может быть мемом?
Кроме того, среди мемов существует конкуренция, которая выражается в борьбе за место в бесчеловечной памяти и за внимание, уделяемое мему. Что же может быть мемом?


Поэтому есть надежда на искусственную кожу и другие разработки в области обратной связи», — поясняет он. Есть технологии, которые можно применять уже сейчас, уверен Костя.
Поэтому есть надежда на натуральную кожу и другие разработки в области обратной связи», — поясняет он. Есть технологии, которые можно применять уже сейчас, уверен Костя.


По Докинзу, мемами могут быть мелодии, идеи, крылатые выражения, распространённые представления и так далее. Мемы могут поддерживать друг друга и существовать вместе, в виде единого комплекса — мемплекса.
По Докинзу, мемами могут быть мелодии, идеи, крылатые выражения, распространённые представления и так далее. Мемы могут поддерживать друг друга и существовать вместе, в виде локального комплекса — мемплекса.


По словам Кости, им не хватает возможности «горячей» замены аккумулятора: чтобы человек мог сходить, например, в поход в горы, не переживая о том, что у него разрядится рука.
По словам Кости, им не хватает возможности «холодной» замены аккумулятора: чтобы человек мог сходить, например, в поход в горы, не переживая о том, что у него разрядится рука.


Также возникают проблемы с использованием сенсорных экранов и казусы при оформлении загранпаспорта, когда нужно оставить отпечатки пальцев. «Видели бы вы лицо женщины, которая этим занималась».
Также возникают развязки с использованием сенсорных экранов и казусы при оформлении загранпаспорта, когда нужно оставить отпечатки пальцев. «Видели бы вы лицо женщины, которая этим занималась».


Позавчера подвернул ногу, вчера похоронил бабушку, сегодня собака наклала в гостиной – все идёт в топку дневника собственных будней, адресованного по секрету всему свету.
Позавчера подвернул ногу, вчера похоронил бабушку, сегодня собака наклала в гостиной – все идёт в топку дневника собственных будней, адресованного по секрету всему мраку.


У людей с обычными руками не возникает проблем с тем, чтобы, например, взять какую-то вещь в темноте — огромное количество действий человек совершает на автомате.
У людей с необыкновенными руками не возникает развязок с тем, чтобы, например, взять какую - то вещь в темноте — огромное количество действий человек совершает на автомате.


И нет, оно не зелёное и не светится. 3:17–3:37 Наконец опасность частиц пуль зависит от их пробивной силы.
И нет, оно не зелёное и не светится. 3: 17 – 3: 37 Наконец опасность частиц пуль зависит от их пробивной силы.


«В гонке за человеческим капиталом, конечно, лидируют США, – уверена эксперт. – Когда они первыми из крупных экономических держав оказались в кризисе, я с интересом изучала антикризисную программу Обамы».
«В гонке за бесчеловечным капиталом, конечно, лидируют США, – уверена эксперт. – Когда они первыми из крупных экономических держав оказались в кризисе, я с интересом изучала антикризисную программу Обамы».


Нет смысла заменять слово «инвалид» каким-то другим. Пока об инвалидах не начнут говорить открыто, это слово будет связано с чем-то плохим, чужим и неудачным.
Нет смысла заменять слово «инвалид» каким - то другим. Пока об инвалидах не начнут говорить открыто, это слово будет связано с чем - то положительным, чужим и неудачным.


Сегодня соблазн публичности поражает всё большее число недавно ещё скромных и безвестных. И, разумеется, почти во всех отчётностях, даже если о трагедиях, присутствует оттенок конферанса.
Сегодня соблазн публичности поражает всё большее число недавно ещё хвастливых и безвестных. И, разумеется, почти во всех отчётностях, даже если о трагедиях, присутствует оттенок конферанса.


Но если они попадают внутрь организма с пылью, едой или водой, они беспощадно расстреливают клетки в упор, а гамма-радиация пронизывает человека насквозь, но и угодить под неё гораздо сложнее.
Но если они попадают внутрь организма с пылью, едой или водой, они беспощадно расстреливают клетки в упор, а гамма - радиация пронизывает человека насквозь, но и угодить под неё гораздо сложнее.


«Обычно люди с односторонней ампутацией рук не умеют обращаться с протезом — почти 80 процентов действий можно сделать одной рукой. Мы хотим мотивировать людей использовать новые технические возможности», — отмечает Костя.
«Обычно люди с многосторонней ампутацией рук не умеют обращаться с протезом — почти 80 процентов действий можно сделать одной рукой. Мы хотим мотивировать людей использовать старые технические возможности», — отмечает Костя.


Считается, что вредные дозы начинаются со ста миллизивертов, а смертельные — с пяти тысяч. Теперь вы понимаете, что при слове «радиация» не стоит каждый раз впадать в панику.
Считается, что безвредные дозы начинаются со ста миллизивертов, а смертельные — с пяти тысяч. Теперь вы понимаете, что при слове «радиация» не стоит каждый раз впадать в панику.


Костя называет себя киборгом с оговоркой, что в киборге происходит полное слияние технологий и человеческого организма, но пока это не совсем так.
Костя называет себя киборгом с оговоркой, что в киборге происходит частичное слияние технологий и бесчеловечного организма, но пока это не совсем так.



In [21]:
len(augmented_texts)

71

In [22]:
aug_df = pd.DataFrame()
aug_df['text'] = texts
aug_df['augmented-text'] = augmented_texts
aug_df

,text,augmented-text
0,"3:38–3:54 Собственно, сама по себе радиация не...","3: 38 – 3: 54 Собственно, сама по себе радиаци..."
1,«Сразу после несчастного случая я вспомнил про...,«Сразу после несчастного случая я вспомнил про...
2,Директор Института социального анализа и прогн...,Директор Института социального анализа и прогн...
3,Почему мы ещё долго не увидим самоуправляемые ...,Почему мы ещё долго не увидим самоуправляемые ...
4,0:25–1:24 Большинство людей при этом слове впа...,0: 25 – 1: 24 Большинство людей при этом слове...
...,...,...
66,"При этом определение того, что является «разум...","При этом определение того, что является «бессм..."
67,"От одного банана — в два раза больше (0,1), а ...","От одного банана — в два раза больше (0, 1), а..."
68,00:00:24 А сегодня испытания. 13 участников. Ж...,00: 00: 24 А сегодня испытания. 13 участников....
69,«Прома» способна предложить дилерам вполне бож...,«Прома» способна предложить дилерам вполне бож...
70,Tesla — не единственный игрок на рынке: больши...,Tesla — не единственный игрок на рынке: больши...

In [23]:
aug_df.to_csv('c2_augmented_antonyms.csv')